import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import ReactQueryProvider from "@/components/providers/react-query-provider";
import ModalProvider from "@/components/providers/modal-provider";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import PusherProvider from "@/components/providers/pusher-provider";

const font = Open_Sans({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
    title: "Discord Clone",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
                <body className={cn("bg-background", font.className)}>
                    <ReactQueryProvider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="dark"
                            enableSystem={false}
                            storageKey="discord-clone-theme"
                        >
                            <ModalProvider />
                            <PusherProvider>{children}</PusherProvider>
                            <Toaster />
                        </ThemeProvider>
                    </ReactQueryProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
